version: "3"

services:
  devopsbingo-backend:
    image: com.cegeka.devopscourse/bingoapp
    environment:
      - SPRING_PROFILES_ACTIVE=container
    ports:
      - "8888:8080"
  devopsbingo-mysql:
    image: mysql:5.7.18
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=devopsbingo
      - lower_case_table_names=1
      - skip-ssl
      - character_set_server=utf8
      - explicit_defaults_for_timestamp